echo "Hello, World!" > hello-world.txt
git init
git add hello-world.txt
git commit -m "첫 번째 커밋: Hello, World! 출력"
git branch -M main
git remote add origin https://github.com/min0125/Homework-6/new/main?filename=.github%2Fworkflows%2Fmain.yml&workflow_template=blank
git push -u origin main
